services:
  mongodb:
    image: mongo
    container_name: events-board-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: eventsboard
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
